# Generated by Django 3.2.12 on 2022-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealSystem', '0002_auto_20220214_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealstatus',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
