# Generated by Django 3.2.12 on 2022-02-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealSystem', '0003_mealstatus_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='department',
            field=models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Eechanical Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Other', 'Other')], max_length=30),
        ),
    ]
