# Generated by Django 3.2.9 on 2022-01-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealSystem', '0003_auto_20220117_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
