# Generated by Django 3.2.9 on 2022-01-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealSystem', '0004_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
